lang: en

project: 
  title: "Sustianable Future"
  type: website
  output-dir: docs


website:
  page-navigation: true
  title: "Homepage"
  site-url: "https://sustainable-future.ca/"
  page-footer:
    left: "Website made with [Quarto](https://quarto.org/) by [Kunal](https://ilovesoils.com/about.html)."

    right:
      - text: English
        href: https://sustainable-future.ca/index.html
      - text: Français
        href: https://sustainable-future.ca/fr/index.html
      - icon: envelope
        href: mailto:info@ilovesoils.com
      - text: "@2024 Sustainable Future. All rights reserved."


  #search:
    #location: navbar
    #type: overlay
    
  navbar:
    left:
      - text: "About Us"
        href: about.qmd
      - text: "Our Services"
        href: services.qmd
      - text: "Careers"
        href: careers.qmd        
      - text: "Why Choose us?"
        href: choose.qmd
      - text: "Contact Us"
        href: contact2.qmd
    right:
      - href: https://sustainable-future.ca/index.html
        text: English
      - href: /fr/index.html
        text: Français 

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual


execute:
  freeze: true
  #increment: true